# -*- coding: utf-8 -*-
"""Reddit Data Ingestion Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5s4-62j2m0hLU21kjMJR_VAt8oClKqv
"""

!pip install praw

import praw
import pandas as pd

# Connect to Reddit API
reddit = praw.Reddit(
    client_id="bTMfdwibLpQwmlt4U6IGLw",
    client_secret="7kPJ4Bowwgo7zhZFWp3enN1KMEuxEA",
    user_agent="script:Data Pipeline:v1.0 (by u/No-Shock1174)"

)
print(reddit.read_only) # fetch data without posting or modifying

# Select the "technology" subreddit to work with

subreddit = reddit.subreddit("technology")

#checking datatypes of the fields
for submission in subreddit.hot(limit=1):
  print(type(submission.id))
  print(type(submission.title))
  print(type(submission.author))
  print(type(submission.score))
  print(type(submission.num_comments))
  print(type(submission.created_utc))
  print(type(submission.selftext))
  print(type(submission.subreddit))

# List to store post data
posts_data = []

# Fetch hot posts
for submission in subreddit.hot(limit=10):
    posts_data.append({
        "id": submission.id,
        "title": submission.title,
        "author": str(submission.author),
        "score": submission.score,
        "num_comments": submission.num_comments,
        "created_utc": submission.created_utc,
        "selftext": submission.selftext,
        "subreddit": str(submission.subreddit)
    })

posts_df = pd.DataFrame(posts_data)

print(posts_df.head())

comments_data = []

for submission in subreddit.hot(limit=10):
    submission.comments.replace_more(limit=0) # Expand all hidden comments to get every comment and reply
    for comment in submission.comments.list():
        comments_data.append({
            "id": comment.id,
            "author": str(comment.author),
            "body": comment.body,
            "score": comment.score,
            "created_utc": comment.created_utc,
            "parent_id": comment.parent_id,
            "link_id": comment.link_id
        })

comments_df = pd.DataFrame(comments_data)
print(comments_df.head())

posts_df.to_csv("reddit_posts.csv", index=False)
comments_df.to_csv("reddit_comments.csv", index=False)